return {
  -- {
  --   "olimorris/codecompanion.nvim",
  --   opts = {
  --     strategies = {
  --       inline = {
  --         adapter = "ollama"
  --       },
  --       chat = {
  --         adapter = "ollama"
  --       }
  --     }
  --   },
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "nvim-treesitter/nvim-treesitter",
  --   }
  -- },
  -- {
  --   {
  --     "echasnovski/mini.diff",
  --     opts = function(plugin)
  --       return {
  --         -- Disabled by default
  --         source = plugin.gen_source.none(),
  --       }
  --     end
  --   },
  -- }
}
